export enum SYSTEM_CODE {
  ALREADY_EXISTS_PROFILE_IN_SYSTEM = 'ALREADY_EXISTS_PROFILE_IN_SYSTEM',
  ALREADY_BLOG_TITLE_IN_SYSTEM = 'ALREADY_BLOG_TITLE_IN_SYSTEM',
  BLOG_NOT_FOUND = 'BLOG_NOT_FOUND',
  PLEASE_UPDATE_SOMETHING = 'PLEASE_UPDATE_SOMETHING',
  SORRY_SOMETHING_WENT_WRONG = 'SORRY_SOMETHING_WENT_WRONG',
  UNAUTHORIZED = 'UNAUTHORIZED',
  BAD_REQUEST = 'BAD_REQUEST',
  FORBIDDEN = 'FORBIDDEN',
  SUCCESS = 'SUCCESS',
}
